version: '3.8'
services:
  employee-db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  admin-db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: admin_db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5433:5433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network

  employee-api:
    build: ./back-end/employee-api
    ports:
      - "8080:8080"
    depends_on:
      - employee-db
    networks:
      - my_network

  admin-api:
    build: ./back-end/admin-api
    ports:
      - "8081:8081"
    depends_on:
      - admin-db
    networks:
      - my_network

networks:
  my_network:
